export const products = [
  {
    id: 1,
    name: 'Grey Female Jeans',
    img: './images/jeans1.jpg',
    price: 400,
    rating: 3,
    quantity: 5,
  },
  {
    id: 2,
    name: 'Blue Male Jeans',
    img: './images/jeans2.jpg',
    price: 160,
    rating: 4,
    quantity: 2,
  },
  {
    id: 3,
    name: 'Dark Male Jeans',
    img: './images/jeans3.jpg',
    price: 320,
    rating: 3,
    quantity: 2,
  },
  {
    id: 4,
    name: 'Blue Female Jeans',
    img: './images/jeans4.jpg',
    price: 155,
    rating: 2,
    quantity: 10,
  },
  {
    id: 5,
    name: 'Female Formal Shoes',
    img: './images/shoes1.jpg',
    price: 550,
    rating: 5,
    quantity: 2,
  },
  {
    id: 6,
    name: 'Nike Male Shoes',
    img: './images/shoes2.jpg',
    price: 300,
    rating: 3,
    quantity: 1,
  },
  {
    id: 7,
    name: 'Red Snikers',
    img: './images/shoes3.jpg',
    price: 130,
    rating: 3,
    quantity: 5,
  },
  {
    id: 8,
    name: 'Female Nike Shoes',
    img: './images/shoes4.jpg',
    price: 390,
    rating: 5,
    quantity: 10,
  },
  {
    id: 9,
    name: 'Green Nike Shoes',
    img: './images/shoes5.jpg',
    price: 330,
    rating: 4,
    quantity: 2,
  },
  {
    id: 10,
    name: 'White T-Shirt',
    img: './images/shirt1.jpg',
    price: 55,
    rating: 3,
    quantity: 10,
  },
  {
    id: 11,
    name: 'Long-sleeve Shirt',
    img: './images/shirt4.jpg',
    price: 60,
    rating: 5,
    quantity: 2,
  },
];
